"""
Reset the bot's state for a fresh start.

WIPES (safe — re-generated by normal trading):
  • SQLite trades / signal_log / daily_summary / market_snapshots / alltime_records
  • Mongo trades / signal_log / daily_journals / option_snapshots / records / weekly_reviews
  • CSV: db/oi_snapshots/*, db/collector_summary.csv, db/option_chain_history.csv,
         db/pcr_historical.csv, db/strategy_log.csv
  • JSON: journals/*.json
  • Angel One error log (db/flags/angel_errors.json)
  • Transient IPC: day_bias.json, sl_orders.json, tp_orders.json, watch_zones.json

KEEPS (user-curated state — never touch):
  • .env (all credentials)
  • config.py (financial parameters)
  • settings.json (min_lots)
  • market_holidays.json (frontend-added holidays)
  • event_blocks.json / event_unblocks.json (custom event dates)
  • backtest_cache/* (historical bars cache — slow to refetch)
  • All logs in logs/YYYY-MM-DD/*.log (Python log files for forensics)

Usage on the droplet:
    docker compose exec api python scripts/reset_for_fresh_start.py --confirm
    docker compose restart api collector

The --confirm flag is required to actually run; without it the script
just prints what it would do.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

BASE = Path(__file__).parent.parent
DRY_RUN = True


def _act(label: str, fn):
    """Run a cleanup step with consistent logging."""
    if DRY_RUN:
        print(f"  [DRY RUN] would {label}")
        return
    try:
        fn()
        print(f"  ✓ {label}")
    except Exception as e:
        print(f"  ✗ {label}: {e}")


# ── 1. SQLite ─────────────────────────────────────────────────────────────────

def clear_sqlite():
    print("\n[SQLite]")
    from core.memory import get_connection
    tables = ["trades", "signal_log", "daily_summary",
              "market_snapshots", "alltime_records"]

    def _truncate():
        with get_connection() as conn:
            for t in tables:
                try:
                    conn.execute(f"DELETE FROM {t}")
                except Exception as e:
                    print(f"    {t}: {e}")
            conn.execute("VACUUM")

    _act(f"truncate {len(tables)} SQLite tables ({', '.join(tables)})", _truncate)


# ── 2. MongoDB ────────────────────────────────────────────────────────────────

def clear_mongo():
    print("\n[MongoDB]")
    from core import mongo
    db = mongo.get_db()
    if db is None:
        print("  (skipped — Mongo not configured / unreachable)")
        return
    collections = ["trades", "signal_log", "daily_journals",
                   "option_snapshots", "records", "weekly_reviews"]
    for col in collections:
        def _del(_col=col):
            res = db[_col].delete_many({})
            print(f"    {_col}: deleted {res.deleted_count} docs")
        _act(f"clear Mongo {col}", _del)


# ── 3. CSVs ───────────────────────────────────────────────────────────────────

def clear_csvs():
    print("\n[CSV files]")
    targets = [
        BASE / "db" / "collector_summary.csv",
        BASE / "db" / "option_chain_history.csv",
        BASE / "db" / "pcr_historical.csv",
        BASE / "db" / "strategy_log.csv",
    ]
    for f in targets:
        if f.exists():
            _act(f"delete {f.relative_to(BASE)}", lambda p=f: p.unlink())

    snap_dir = BASE / "db" / "oi_snapshots"
    if snap_dir.exists():
        files = list(snap_dir.glob("*.csv"))
        for f in files:
            _act(f"delete {f.relative_to(BASE)}", lambda p=f: p.unlink())


# ── 4. JSON state ─────────────────────────────────────────────────────────────

def clear_json_state():
    print("\n[JSON files]")
    journals_dir = BASE / "journals"
    if journals_dir.exists():
        for f in list(journals_dir.glob("*.json")):
            _act(f"delete {f.relative_to(BASE)}", lambda p=f: p.unlink())


# ── 5. Transient IPC flags + Angel error log ──────────────────────────────────

def clear_transient_state():
    print("\n[Transient IPC + error log]")
    flags_dir = BASE / "db" / "flags"
    targets = [
        "day_bias.json",
        "sl_orders.json",
        "tp_orders.json",
        "watch_zones.json",
        "force_trade.json",
        "pause",
        "resume",
        "angel_errors.json",
    ]
    for name in targets:
        f = flags_dir / name
        if f.exists():
            _act(f"delete db/flags/{name}", lambda p=f: p.unlink())


# ── 6. Backup before wipe ────────────────────────────────────────────────────

def backup():
    """Create timestamped backup of trading.db, journals/, logs/paper_comparison.json."""
    print("\n[Backup]")
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_root = BASE / "db" / f"backup-{ts}"

    def _do_backup():
        backup_root.mkdir(parents=True, exist_ok=True)
        # SQLite
        db_file = BASE / "db" / "trading.db"
        if db_file.exists():
            shutil.copy(db_file, backup_root / "trading.db")
        # Journals
        journals_dir = BASE / "journals"
        if journals_dir.exists():
            shutil.copytree(journals_dir, backup_root / "journals", dirs_exist_ok=True)
        # Snapshot CSVs
        snap_dir = BASE / "db" / "oi_snapshots"
        if snap_dir.exists():
            shutil.copytree(snap_dir, backup_root / "oi_snapshots", dirs_exist_ok=True)
        print(f"    backup root: {backup_root}")

    _act(f"create backup at db/backup-{ts}/", _do_backup)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    global DRY_RUN
    p = argparse.ArgumentParser()
    p.add_argument("--confirm", action="store_true",
                   help="actually run; without this it's a dry-run")
    p.add_argument("--no-backup", action="store_true",
                   help="skip the safety backup (NOT recommended)")
    args = p.parse_args()

    DRY_RUN = not args.confirm
    mode = "LIVE RUN — modifying disk + Mongo" if args.confirm else "DRY RUN — no changes"
    print(f"\n  RESET FOR FRESH START — {mode}\n")

    if not args.no_backup:
        backup()
    clear_sqlite()
    clear_mongo()
    clear_csvs()
    clear_json_state()
    clear_transient_state()

    print("\nDone.")
    if DRY_RUN:
        print("  Re-run with --confirm to actually execute.")
    else:
        print("  Restart the bot:")
        print("    docker compose restart api collector")


if __name__ == "__main__":
    main()
